"""
Rule catalogue: for every finding the rule engine can raise, the rule it applies, the standard behind
it, and the concrete impact. Used by the evidence chains and the posture explanation.
"""
from __future__ import annotations

# finding id → (rule statement, reference, impact)
RULES: dict[str, tuple[str, str, str]] = {
    "CRYPTO-001": ("ESP must encrypt the payload", "RFC 4303 §3.2 · RFC 8221 §5",
                   "Anyone on the path can read every packet in the tunnel: integrity without confidentiality."),
    "CRYPTO-002": ("Ciphers below 80-bit strength are prohibited", "NIST SP 800-131A r2 · RFC 8221",
                   "Traffic keys can be brute-forced with commodity hardware."),
    "CRYPTO-003": ("64-bit block ciphers are deprecated", "NIST SP 800-131A r2 §2 · Sweet32 (CVE-2016-2183)",
                   "Birthday attacks recover plaintext after ~32 GB under one key; TDEA is disallowed after 2023."),
    "CRYPTO-004": ("Prefer authenticated encryption (AEAD)", "RFC 8221 §5 · RFC 8247 §2.2",
                   "Secure, but encrypt-then-MAC is slower and has more room for implementation error than AEAD."),
    "CRYPTO-005": ("AEAD ciphers satisfy current guidance", "RFC 8221 · RFC 8247", "None: modern authenticated encryption."),
    "CRYPTO-007": ("Cipher must be observable to be assessed", "Passive analysis limit",
                   "The encryption strength cannot be verified from this capture."),
    "KE-001": ("Key exchange must provide ≥ 112-bit security", "NIST SP 800-57 Pt1 r5 Table 2 · RFC 8247 §2.4",
               "Groups 1/2 are in reach of precomputation (Logjam): a nation-state adversary can derive session keys."),
    "KE-002": ("Key exchange must provide ≥ 112-bit security", "NIST SP 800-57 Pt1 r5 Table 2 · RFC 8247 §2.4",
               "Below-minimum DH strength shortens the time recorded traffic stays confidential."),
    "KE-003": ("112-bit key exchange acceptable until 2030", "NIST SP 800-57 Pt1 r5 §5.6.3",
               "Recorded traffic becomes decryptable earlier than with 128-bit+ groups."),
    "KE-004": ("Key exchange ≥ 128-bit security", "NIST SP 800-57 Pt1 r5", "None."),
    "KE-005": ("Plan post-quantum key exchange for long-lived secrets", "RFC 9370 · CNSA 2.0",
               "Harvest-now-decrypt-later: traffic recorded today may be decrypted by a future quantum computer."),
    "KE-006": ("Initiators must not offer algorithms weaker than policy", "RFC 8247 §2 · downgrade resistance",
               "A misconfigured or compromised responder can select the weak fallback suite."),
    "KE-007": ("DH preferences should match on both peers", "RFC 7296 §1.2", "An extra round trip; no direct weakness."),
    "PFS-001": ("Child SAs should run a fresh DH exchange (PFS)", "NIST SP 800-77r1 §4.4 · RFC 7296 §1.3.1",
                "Compromise of one IKE SA key exposes every Child SA derived from it, including past traffic."),
    "PFS-002": ("Child SAs run a fresh DH exchange", "NIST SP 800-77r1 §4.4", "None: rekeys are forward secret."),
    "PFS-003": ("PFS can only be seen during a rekey", "Passive analysis limit",
                "Forward secrecy cannot be verified from this capture."),
    "AUTH-001": ("Aggressive Mode must not be used with pre-shared keys", "NIST SP 800-77r1 §4.2 · CVE-2002-1623",
                 "The PSK hash can be cracked offline, after which an attacker can impersonate either gateway."),
    "AUTH-002": ("PSK strength depends on key entropy", "NIST SP 800-77r1 §4.2",
                 "A guessable PSK allows active impersonation; key rotation is manual."),
    "AUTH-003": ("Public-key or EAP peer authentication", "RFC 7296 §2.15", "None."),
    "AUTH-004": ("HMAC-MD5 is prohibited for integrity", "RFC 8221 §6 · RFC 8247 §2.3",
                 "Packet integrity rests on a hash with broken collision resistance; forbidden by current profiles."),
    "AUTH-005": ("HMAC-SHA1 is being phased out", "RFC 8221 §6 (MUST-) · RFC 8247",
                 "Still unbroken as an HMAC, but fails modern compliance profiles and CNSA."),
    "LIFE-001": ("IKE SA lifetime ≤ 24 h", "NIST SP 800-77r1 §4.5",
                 "Long-lived keying material widens the window in which a stolen or cracked key is useful."),
    "LIFE-002": ("Child SA lifetime ≤ 8 h", "NIST SP 800-77r1 §4.5", "More traffic is protected by a single key."),
    "LIFE-003": ("IKE SA lifetime ≤ 24 h", "NIST SP 800-77r1 §4.5", "None."),
    "LIFE-004": ("Rekey before the 32-bit sequence counter wraps", "RFC 4303 §3.3.3",
                 "Without ESN the SA must be torn down; a wrap would reuse sequence numbers."),
    "LIFE-005": ("Lifetimes are only visible across a rekey", "Passive analysis limit",
                 "Key lifetime cannot be verified from this capture."),
    "REPLAY-001": ("A (SPI, sequence) pair must not repeat", "RFC 4303 §3.4.3",
                   "Replayed packets reach the receiver; without an enforced window they are processed twice."),
    "REPLAY-002": ("The sequence counter must not cycle within an SA", "RFC 4303 §3.3.3",
                   "Suggests anti-replay is disabled or keys are manual: replayed packets would be accepted."),
    "REPLAY-003": ("Replay window must cover reordering depth", "RFC 4303 §3.4.3",
                   "Legitimate late packets are dropped, which looks like loss to the application."),
    "REPLAY-004": ("Sequence numbers increase per SA", "RFC 4303 §3.3.3", "None."),
    "CFG-001": ("Use IKEv2", "RFC 9395 (IKEv1 Historic) · NIST SP 800-77r1",
                "IKEv1 lacks IKEv2's DoS protection and has more error-prone negotiation."),
    "CFG-002": ("Use IKEv2", "RFC 9395", "None."),
    "CFG-003": ("Gateways should use tunnel mode", "RFC 4301 §4.1",
                "True endpoints are visible and site-to-site addressing is exposed."),
    "CFG-004": ("Negotiations should succeed", "RFC 7296 §3.10.1", "Mismatched or probing peers are present."),
    "CFG-005": ("Configuration must meet IETF / NIST profiles", "RFC 8221 · RFC 8247 · NIST SP 800-77r1",
                "The deployment fails published guidance and would not pass an audit."),
    "CFG-006": ("Responder may demand cookies under load", "RFC 7296 §2.6", "None: DoS protection is active."),
    "META-001": ("Peer identities must be encrypted", "RFC 2409 §5.4 (Aggressive Mode) · RFC 7296",
                 "User or gateway names are visible to any observer, enabling targeting and PSK attacks."),
    "META-002": ("Do not advertise the implementation", "Operational hardening",
                 "An attacker learns the product and can pick matching exploits."),
    "META-003": ("Traffic analysis resistance for sensitive tunnels", "RFC 4303 §2.7 (TFC padding)",
                 "An observer can tell what kind of activity runs in the tunnel, and when."),
    "META-004": ("NAT traversal reveals topology", "RFC 3948", "Reveals that a peer sits behind NAT."),
    "META-005": ("Transport mode exposes endpoints", "RFC 4301 §4.1", "Reveals exactly which hosts communicate."),
    "META-006": ("CERTREQ carries CA hashes in cleartext", "RFC 7296 §3.7", "Reveals which CA the peer trusts."),
}


def rule_for(finding_id: str) -> tuple[str, str, str]:
    return RULES.get(finding_id, ("Rule-engine check", "SecurIQ rule engine", "See the finding description."))
